image: rust:latest

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  CARGO_TERM_COLOR: always

before_script:
  - dnf install -y mingw-w64
  - rustup target add x86_64-pc-windows-gnu

cache:
  paths:
    - target/
    - cargo/

stages:
  - build

build-linux:
  stage: build
  script:
    - rustc --version
    - cargo build --release
  artifacts:
    paths:
      - target/release/letbuildirtplee
    expire_in: 1 week
  only:
    - main
    - master
    - merge_requests

build-windows:
  stage: build
  script:
    - rustc --version
    - cargo build --release --target x86_64-pc-windows-gnu
  artifacts:
    paths:
      - target/x86_64-pc-windows-gnu/release/letbuildirtplee.exe
    expire_in: 1 week
  only:
    - main
    - master
    - merge_requests
